[[library]]
type="file"
name="net"
path="../net"
includes=[
  "net/conn.hpp",
  "net/server.hpp"
]

[[library]]
type="file"
name="sched"
path="../sched"
includes=[
  "sched/sched.hpp"
]

[[library]]
type="file"
name="ser"
path="../ser"
includes=[
  "ser/ser.hpp"
]
